### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Roroca-1** [lscambo13/ElegantMustard#4]
How to remove background color(the darker dim) for the Slimmer variant?

**Comment by lscambo13** [comment]
It's easy. Follow the steps below:

0. Open RTSS overlay editor (I assume you already know how to do this)
1. Double click where the arrow points to
2. Click on black color box
3. Reduce (A)lpha (reduce to zero to fully remove the color)
4. Click OK
5. Save.

![change color rtss overlay](https://github.com/user-attachments/assets/a71a6772-92fc-4c99-94d7-901d202b0897)
